[broker]
BROKER = "alpaca"

[alpaca]
ALPACA_API_KEY = "PKFXJ6MZQAJLCXZUXRJQ"
ALPACA_SECRET_KEY = "tLzA3QOUJcAGuDGdKIBcDmSQhNc37s46UryPcAFl"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_PAPER = true

[oanda]
OANDA_ACCESS_TOKEN = "fe8193fed7205ea42ab6014ed201b904-0600fb12752223rdce6b51bbb"
OANDA_ACCOUNT_ID = "your_oanda_account_id_here"
OANDA_ENVIRONMENT = "practice"

[ccxt]
CCXT_EXCHANGE = "binance"
CCXT_API_KEY = "your_ccxt_api_key_here"
CCXT_SECRET = "your_ccxt_secret_here"
CCXT_SANDBOX = true

[trading]
INSTRUMENT = "EUR_USD"
GRANULARITY = "M1"
RISK_PER_TRADE = 0.005
MAX_DAILY_DRAWDOWN = 0.02
UNITS_CAP = 20000

[strategy]
SLOW_SMA = 50
FAST_SMA = 20
ATR_WINDOW = 14
ATR_MULTIPLIER = 2.0
